language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - android-19
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-28
  - sys-img-armeabi-v7a-google_apis-19

  licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
before_script:
#  Gradle
- wget http://services.gradle.org/distributions/gradle-4.10.1-bin.zip
- unzip gradle-4.10.1-bin.zip
- export GRADLE_HOME=$PWD/gradle-4.10.1
- export PATH=$GRADLE_HOME/bin:$PATH
# Emulator
- echo no | android create avd --force -n test -t "android-19" --abi armeabi-v7a --tag google_apis
- emulator -avd test -no-skin -no-window &
- android-wait-for-emulator
- adb shell settings put global window_animation_scale 0 &
- adb shell settings put global transition_animation_scale 0 &
- adb shell settings put global animator_duration_scale 0 &
- adb shell input keyevent 82 &
script:
- gradle assembleDebug -PdisablePreDex
- gradle assembleDebugAndroidTest -PdisablePreDex
- adb install app/build/outputs/apk/debug/app-debug.apk
- adb install app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
- gradle build check
- gradle build test
- gradle build connectedCheck